[package]
name = "playdsp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
rayon = "1.10.0"
chrono = "0.4.38"
bwavfile = "2.0.1"
cc = "1.1.31"
home = "0.5.9"

[build-dependencies]
cc = "1.1.31"